# make file for assignment 1 (sorts, stacks, and queues)
# source for make file explanation: https://bytes.usc.edu/cs104/wiki/makefile/
program1:
	g++ -o program1 main1.cpp readFile.cpp Node.cpp Sorts.cpp

clean:
	rm program1