# make file for assignment 2 (Searches and Hashing)
# source for make file explanation: https://bytes.usc.edu/cs104/wiki/makefile/
program2:
	g++ -o program2 main2.cpp readFile.cpp MergeSort.cpp

clean:
	rm program2